CREATE DATABASE LoanDB;

USE LoanDB;

CREATE TABLE loans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    loan_date DATE NOT NULL DEFAULT (CURRENT_DATE)
);
